### PR TITLE
Migrate to LLVM v6.x (svn)

### PR DESCRIPTION
**Pull request by xiangzhai**
Hi flang developers,

Please review my patch, and give me some suggestion, thanks a lot!

Regards,
Leslie Zhai

### CODE REVIEW

**Comment by xiangzhai** [comment]
Hi @krytarowski

Please review the patch, I will update it as your suggestion, thanks a lot!

Regards,
Leslie Zhai

**Comment by krytarowski** [comment]
@hfinkel ^

**Comment by krytarowski** [comment]
(I'm not a member of the flang-compiler team to review it myself)

**Comment by sscalpone** [comment]
We're working on the 5.0 integration now.  We'll take a look after that's committed.

**Comment by xiangzhai** [comment]
Hi @sscalpone 

> We're working on the 5.0 integration now. We'll take a look after that's committed.

I will rebase my patch with your v5.x integration.

Regards,
Leslie Zhai

**Pull request closed without merging**
