### PR TITLE
Windows3

### PR DESCRIPTION
**Pull request by ghost**
DO NOT DELETE THIS BRANCH

### CODE REVIEW

**Comment by ghost** [comment]
@isuruf Can you check this? It appears to build now.

**Comment by isuruf** [comment]
Looks good to me. Can you cleanup the commits?

**Comment by ghost** [comment]
Sure.

**Comment by ghost** [comment]
Actually I just realized that it would not be a good idea to cleanup the commits on this branch because conda-forge depends on e39d1b1. I'll reopen this with another branch.

**Pull request closed without merging**
